### ISSUE TITLE
Repo structure on github

### ISSUE THREAD

**Issue by rimmesbe** [Buckshotdesigns/Buckshotdesigns.github.io#1]
Okay so you have put all your projects into the github.io repo. This is incorrect. Each of these projects should be in their own repository. You can still host them on pages by going into that repo's settings and selecting 'master branch' under the githup pages section.

https://github.com/Buckshotdesigns/Buckshotdesigns.github.io

**Comment by Buckshotdesigns** [comment]
got it issue fixed
